[project]
name = "Horrible Menu"
version = ""
repository = "https://github.com/CubicCommunity/HorribleMenu"
tree = "https://github.com/CubicCommunity/HorribleMenu/tree/main"
icon = "logo.png"

[[docs]]
name = "Horrible"
dir = "include"
include = ["horrible/*.h*"]
exclude = ["horrible/DLL.hpp"]

[cmake]
config-args = [
    "-G",
    "Ninja",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_CXX_COMPILER=clang++",
    "-DCMAKE_C_COMPILER=clang",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
    "-DGEODE_CODEGEN_CMAKE_ARGS=-DCMAKE_CXX_COMPILER=clang++;-DCMAKE_C_COMPILER=clang",
]
build-dir = "build-docs"
infer-args-from = "src/API.cpp"
